[profile.default]
solc = '0.8.17'
optimizer = true
optimizer_runs = 4_294_967_295
bytecode_hash = 'none'
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
remappings = ['seaport-types/=node_modules/seaport-types/','create2-helpers/=lib/create2-helpers/','forge-std/=lib/forge-std/src/']
fs_permissions = [{access = 'read', path = './out_deploy/'}, {access='read', path='./out/'}]

[profile.precompile-conduit]
solc = '0.8.14'
src = 'src/conduit/'
out = 'out_deploy'
test = 'src/conduit/'
optimizer_runs = 1000000

[profile.precompile-seaport]
out = 'out_deploy'

[profile.deploy]
via_ir = false

[fmt]
line_length = 80