[profile.default]
solc = '0.8.17'
optimizer = true
optimizer_runs = 4_294_967_295
bytecode_hash = 'none'
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
remappings = ['seaport-types/=lib/seaport-types/','create2-helpers/=lib/create2-helpers/','forge-std/=lib/forge-std/src/']
fs_permissions = [{access = 'read', path = 'out_deploy'}]


[profile.deploy]
via_ir = false
src='script'

[fmt]
line_length = 80